### PR TITLE
Add upper underscore case support.

### PR DESCRIPTION
**Pull request by andrew3886**
Hello @koop, 

Please review the following commits I made in branch 'andrew-upperUnderscoreCase'.

54978ea9a9a2f167025c6ee22c3b8863dbecfbe8 (2015-12-08 13:37:57 -0800)
Add upper underscore case support.

R=@koop

TESTED=case test added.

### CODE REVIEW

**Comment by koop** [comment]
why did you change TitleCase to UpperCamelCase? they're synonymous, afaik.

**Comment by andrew3886** [comment]
Because of a temporary misguided sense of naming conventions (http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/CaseFormat.html). I have since gotten over it, because it makes things unnecessarily complicated.

**Comment by andrew3886** [comment]
cc @joy4luck

**Comment by koop** [comment]
LGTM

**Pull request merged**
